url-config-server: http://localhost:8888
#Name of app is important will be used
spring:
  application:
    name: discovery-service

#optional means if we can not find config do not fail use the local
  config:
    import: optional:configserver:${url-config-server}


