server:
  port: 8888


logging:
  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] [%thread] %-5level %logger{36} - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] [%thread] %-5level %logger{36} - %msg%n"
    correlation: " %X{correlationId} "


spring:
  application:
    name: config-server
  profiles:
    active: native


#classpath ==maps to==> src.main.resources , creating a folder called configurations
#classpath ==> same location where application.properties is
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations




