url-config-server: http://localhost:8888


#Name of app is important will be used
spring:
  application:
    name: customer-service

  #optional means if we can not find config do not fail use the local
  config:
    import: optional:configserver:${url-config-server}



#management:
#  endpoint:
#    health:
#      show-details: always
#    metrics:
#      enable: true
#  endpoints:
#    web:
#      exposure:
#        include: '*'
  #promethus exposing metrics

#    web:
#      exposure:
#      include: "*"
#  endpoint:
#    #    prometheus:
#    #      enabled: true
#    #      metrics:
#    #        enabled: true
#    health:
#      show-details: always



#application:
#  config:
#    customer-url: http://localhost:8222/api/v1/customer
#    payment-url: http://localhost:8222/api/v1/payment
#debug: true
#    product-url: http://localhost:8222/api/v1/product